server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: location-service
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/api/v1/locations/**
        
        - id: ride-service
          uri: lb://RIDE-SERVICE
          predicates:
            - Path=/api/v1/rides/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
